version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-3dprint-calc
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: print3d_calc
      MYSQL_USER: calc_user
      MYSQL_PASSWORD: calc_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
